global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: node
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml

  - job_name: wallet
    scrape_interval: 1m
    static_configs:
      - targets:
          - wallet-exporter:9101

  - job_name: reward
    scrape_interval: 1m
    static_configs:
      - targets:
          - reward-exporter:9102
